//! Known-answer tests shared with the Python reference implementation.
//!
//! The vectors in `../djames-py/kat/*.rsp` are generated by `djames-py`. That
//! this crate reproduces them bit for bit -- public key digest and every
//! signature -- is the interoperability guarantee: two implementations
//! written independently against `d-james-spec.md` agree on every byte.

use djames::{keygen, params, scheme, sign, verify};

struct Vector {
    name: String,
    seed: Vec<u8>,
    pk_len: usize,
    pk_digest: String,
    sigs: Vec<(Vec<u8>, Vec<u8>)>,
}

fn unhex(s: &str) -> Vec<u8> {
    let s = s.trim();
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[2 * i..2 * i + 2], 16).unwrap())
        .collect()
}

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{x:02x}")).collect()
}

fn parse(src: &str) -> Vec<Vector> {
    let mut out: Vec<Vector> = Vec::new();
    let mut pending_msg: Option<Vec<u8>> = None;
    for line in src.lines() {
        let Some((key, val)) = line.split_once(" = ") else {
            continue;
        };
        match key.trim() {
            "name" => out.push(Vector {
                name: val.trim().to_string(),
                seed: Vec::new(),
                pk_len: 0,
                pk_digest: String::new(),
                sigs: Vec::new(),
            }),
            "seed" => out.last_mut().unwrap().seed = unhex(val),
            "pk_len" => out.last_mut().unwrap().pk_len = val.trim().parse().unwrap(),
            "pk_sha3_256" => out.last_mut().unwrap().pk_digest = val.trim().to_string(),
            "msg" => pending_msg = Some(unhex(val)),
            "sig" => {
                let m = pending_msg.take().unwrap();
                out.last_mut().unwrap().sigs.push((m, unhex(val)));
            }
            _ => {}
        }
    }
    out
}

fn run(src: &str, resign: bool) {
    let vectors = parse(src);
    assert!(!vectors.is_empty());
    for v in &vectors {
        let p = params::by_name(&v.name).unwrap_or_else(|| panic!("unknown set {}", v.name));
        let (pk, sk) = keygen(p, &v.seed).unwrap();
        let raw = pk.to_bytes();
        assert_eq!(raw.len(), v.pk_len, "{}: public key length", v.name);
        assert_eq!(
            hex(&scheme::pk_digest(&pk)),
            v.pk_digest,
            "{}: public key digest",
            v.name
        );

        // The serialized key must round-trip and verify identically.
        let reloaded = djames::PublicKey::from_bytes(p, &raw).unwrap();
        assert_eq!(reloaded.to_bytes(), raw, "{}: pk round-trip", v.name);

        for (i, (msg, want)) in v.sigs.iter().enumerate() {
            assert!(
                verify(p, &pk, msg, want),
                "{}: recorded signature {i}",
                v.name
            );
            assert!(
                verify(p, &reloaded, msg, want),
                "{}: via reloaded pk {i}",
                v.name
            );
            if resign {
                let got = sign(p, &sk, msg).unwrap();
                assert_eq!(hex(&got), hex(want), "{}: re-signed {i}", v.name);
            }
            // Negative checks.
            assert!(!verify(p, &pk, b"not the message", want));
            let mut bad = want.clone();
            bad[0] ^= 1;
            assert!(!verify(p, &pk, msg, &bad));
            assert!(!verify(p, &pk, msg, &vec![0u8; want.len()]));
        }
    }
}

#[test]
fn toy_vectors() {
    run(include_str!("../../djames-py/kat/toy.rsp"), true);
}

/// The real F_2 parameter sets, with signatures. Long-running, so opt in:
/// `cargo test --release -- --include-ignored`
#[test]
#[ignore]
fn q2_vectors() {
    run(include_str!("../../djames-py/kat/q2.rsp"), true);
}

/// Key generation across all twenty real parameter sets.
#[test]
#[ignore]
fn keygen_vectors() {
    run(include_str!("../../djames-py/kat/keygen.rsp"), false);
}
