"""Parameter sets for James and D-James (ePrint 2026/1650, Tables 3-6).

Two families:

  James    HFE-_IP.  The public key is m quadratic forms in the n signature
           variables and verification checks P(a) = Hash(msg).
  D-James  the same plus *Dragon* terms -- bilinear couplings between the
           signature variables and the hash variables -- which decouple the
           number of public equations from the hash length.  The public system
           is homogeneous and verification checks P(a, b) = 0.

Two places where the paper's tables are internally inconsistent; both are
resolved here in favour of the defining relations, and flagged in README.md:

  * Table 4, q = 4 lists m = 180 with n = 223, a = 53, but the table's own
    header defines m = n - a = 170.  We take m = 170.
  * Table 3, q = 4 lists the central monomials as "X^3, X^17".  X^3 is not of
    the form X^(q^i + q^j) over F_4, and every other row of every table uses
    X^2 = X^(q^0 + q^0) as its low monomial.  We read it as X^2.
"""

import json
import os

_FIELDPOLY = None


def field_polynomial(q, n):
    """The canonical field polynomial for K = F_q^n, as [c_0, ..., c_{n-1}].

    Cached in fieldpoly.json; regenerated by tools/gen_fieldpolys.py.  The
    search itself is deterministic, so the cache only ever saves time.
    """
    global _FIELDPOLY
    if _FIELDPOLY is None:
        path = os.path.join(os.path.dirname(__file__), "fieldpoly.json")
        if os.path.exists(path):
            with open(path) as f:
                _FIELDPOLY = json.load(f)
        else:
            _FIELDPOLY = {}
    key = "%d,%d" % (q, n)
    if key not in _FIELDPOLY:
        from .ff import find_irreducible
        _FIELDPOLY[key] = find_irreducible(q, n)
    return _FIELDPOLY[key]


class Params:
    """One parameter set.

    q   base field size            n   degree of K = F_q^n, = signature length
    a   minus modifiers            m   published equations, = n - a
    r   IP rank                    D   central degree, = q^d + 1
    ny  hash length in F_q symbols (D-James only; None for James)
    monomials  the (i, j) with a nonzero lambda_{i,j} X^(q^i + q^j) in H
    """

    def __init__(self, name, scheme, q, n, a, r, D, monomials, ny=None):
        assert scheme in ("james", "d-james")
        assert (scheme == "d-james") == (ny is not None)
        self.name, self.scheme = name, scheme
        self.q, self.n, self.a, self.r, self.D, self.ny = q, n, a, r, D, ny
        self.m = n - a
        d = 0
        while q ** d + 1 < D:
            d += 1
        if q ** d + 1 != D:
            raise ValueError("D = %d is not of the form q^d + 1" % D)
        self.d = d
        for (i, j) in monomials:
            assert 0 <= i <= j <= d and q ** i + q ** j <= D, (name, i, j)
        self.monomials = list(monomials)
        assert self.m > 0 and self.r >= 1

    # Number of public-key coefficients, and the exact sizes they imply.
    @property
    def n_aa(self):
        return self.n * (self.n + 1) // 2

    @property
    def n_ab(self):
        return 0 if self.ny is None else self.n * self.ny

    @property
    def pk_coeffs(self):
        return self.n_aa + self.n_ab

    @property
    def sig_bits(self):
        """ceil(log2(q^n)) -- the signature is n symbols of F_q."""
        return (self.q ** self.n - 1).bit_length()

    @property
    def pk_bits(self):
        return self.pk_coeffs * self.m * _log2q_bits(self.q)

    @property
    def sig_bytes(self):
        """Exact serialized signature length."""
        from .codec import vec_bytes
        return vec_bytes(self.n, self.q)

    @property
    def fpoly(self):
        return field_polynomial(self.q, self.n)

    def tag(self):
        """Domain-separation tag: everything that changes the key derivation.

        Printable ASCII with an explicit grammar -- no language's `repr` -- so
        that a second implementation can reproduce the exact bytes:

            D-James/v1/<scheme>/q<q>/n<n>/a<a>/r<r>/D<D>/ny<ny>/mon<i>-<j>[.<i>-<j>]...

        every number in plain decimal, no spaces, and ny = 0 for James.
        """
        mon = ".".join("%d-%d" % (i, j) for (i, j) in self.monomials)
        return ("D-James/v1/%s/q%d/n%d/a%d/r%d/D%d/ny%d/mon%s"
                % (self.scheme, self.q, self.n, self.a, self.r, self.D,
                   self.ny or 0, mon)).encode()

    def __repr__(self):
        return ("<%s %s q=%d m=%d n=%d a=%d ny=%s r=%d D=%d>"
                % (self.name, self.scheme, self.q, self.m, self.n, self.a,
                   self.ny, self.r, self.D))


def _log2q_bits(q):
    import math
    return math.log2(q)


# The low monomial is X^(q^0 + q^0) = X^2 except over F_2, where that is
# X^(q^1) -- a linear map, useless as a quadratic term -- so F_2 uses X^3.
def _mon(q, d):
    lo = (0, 1) if q == 2 else (0, 0)
    return [lo, (0, d)]


_SETS = {}


def _add(p):
    _SETS[p.name] = p
    return p


# --- Table 3: D-James, 128-bit ------------------------------------------
_add(Params("d-james-128-q2", "d-james", 2, 189, 27, 2, 5, _mon(2, 2), ny=256))
_add(Params("d-james-128-q4", "d-james", 4, 105, 21, 2, 17, _mon(4, 2), ny=128))
_add(Params("d-james-128-q5", "d-james", 5, 94, 21, 2, 6, _mon(5, 1), ny=111))
_add(Params("d-james-128-q13", "d-james", 13, 77, 21, 2, 14, _mon(13, 1), ny=70))
_add(Params("d-james-128-q23", "d-james", 23, 74, 21, 2, 24, _mon(23, 1), ny=57))

# --- Table 4: D-James, 256-bit ------------------------------------------
_add(Params("d-james-256-q2", "d-james", 2, 390, 66, 2, 5, _mon(2, 2), ny=512))
_add(Params("d-james-256-q4", "d-james", 4, 223, 53, 2, 17, _mon(4, 2), ny=256))
_add(Params("d-james-256-q5", "d-james", 5, 206, 53, 2, 6, _mon(5, 1), ny=221))
_add(Params("d-james-256-q13", "d-james", 13, 171, 53, 2, 14, _mon(13, 1), ny=139))
_add(Params("d-james-256-q23", "d-james", 23, 163, 53, 2, 24, _mon(23, 1), ny=114))

# --- Table 5: James, 128-bit --------------------------------------------
_add(Params("james-128-q2", "james", 2, 283, 27, 2, 5, _mon(2, 2)))
_add(Params("james-128-q4", "james", 4, 149, 21, 2, 17, _mon(4, 2)))
_add(Params("james-128-q5", "james", 5, 132, 21, 2, 6, _mon(5, 1)))
_add(Params("james-128-q13", "james", 13, 91, 21, 2, 14, _mon(13, 1)))
_add(Params("james-128-q23", "james", 23, 78, 21, 2, 24, _mon(23, 1)))

# --- Table 6: James, 256-bit --------------------------------------------
_add(Params("james-256-q2", "james", 2, 578, 66, 2, 5, _mon(2, 2)))
_add(Params("james-256-q4", "james", 4, 309, 53, 2, 17, _mon(4, 2)))
_add(Params("james-256-q5", "james", 5, 274, 53, 2, 6, _mon(5, 1)))
_add(Params("james-256-q13", "james", 13, 192, 53, 2, 14, _mon(13, 1)))
_add(Params("james-256-q23", "james", 23, 167, 53, 2, 24, _mon(23, 1)))

# --- Toy sets: correctness tests only, no security whatsoever ------------
# Large q keeps r = 1 here: signing costs q^r root-findings and 23^2 = 529 of
# them is not a unit test.
_add(Params("toy-d-james-q2", "d-james", 2, 32, 6, 2, 5, _mon(2, 2), ny=48))
_add(Params("toy-d-james-q4", "d-james", 4, 24, 5, 2, 17, _mon(4, 2), ny=24))
_add(Params("toy-d-james-q5", "d-james", 5, 21, 4, 2, 6, _mon(5, 1), ny=24))
_add(Params("toy-d-james-q13", "d-james", 13, 18, 4, 1, 14, _mon(13, 1), ny=16))
_add(Params("toy-d-james-q23", "d-james", 23, 16, 4, 1, 24, _mon(23, 1), ny=14))
_add(Params("toy-james-q2", "james", 2, 32, 6, 2, 5, _mon(2, 2)))
_add(Params("toy-james-q4", "james", 4, 24, 5, 2, 17, _mon(4, 2)))
_add(Params("toy-james-q5", "james", 5, 21, 4, 2, 6, _mon(5, 1)))
_add(Params("toy-james-q13", "james", 13, 18, 4, 1, 14, _mon(13, 1)))
_add(Params("toy-james-q23", "james", 23, 16, 4, 1, 24, _mon(23, 1)))


def get(name):
    return _SETS[name]


def names(prefix=""):
    return sorted(k for k in _SETS if k.startswith(prefix))


ALL = _SETS
